name: man_page
description: A terminal Help app

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  line_icons: ^2.0.1
  http: ^0.13.4
  salomon_bottom_bar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Anonymous Pro
      fonts:
        - asset: fonts/AnonymousPro-Regular.ttf
    - family: Fant Sans
      fonts:
        - asset: fonts/Fantasque-Sans-Mono-Reg-NF.ttf
    - family: Monoid
      fonts:
        - asset: fonts/Monoid-Regular-NF.ttf
    - family: Victor Mono
      fonts:
        - asset: fonts/VictorMono-Regular.ttf